name = "sm-tx"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "sm-tx-events"
database_id = "3c83f9e8-f37c-4d76-9548-a085f7892ade"

[vars]
API_KEY = "smtx-internal-2026"
